// Mocks generated by Mockito 5.4.6 from annotations
// in task_master/test/services/import_export_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_master/core/constants/enums.dart' as _i5;
import 'package:task_master/data/datasources/local/task_local_data_source.dart'
    as _i2;
import 'package:task_master/data/models/task_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDataSource extends _i1.Mock
    implements _i2.TaskLocalDataSource {
  MockTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertTask(_i4.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#insertTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.TaskModel?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i3.Future<_i4.TaskModel?>.value(),
          )
          as _i3.Future<_i4.TaskModel?>);

  @override
  _i3.Future<List<_i4.TaskModel>> getTasks({
    int? offset = 0,
    int? limit = 20,
    _i5.TaskStatus? status,
    _i5.TaskPriority? priority,
    List<String>? tags,
    String? searchQuery,
    String? sortBy,
    bool? ascending = true,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {
              #offset: offset,
              #limit: limit,
              #status: status,
              #priority: priority,
              #tags: tags,
              #searchQuery: searchQuery,
              #sortBy: sortBy,
              #ascending: ascending,
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i3.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i4.TaskModel>>);

  @override
  _i3.Future<void> updateTask(_i4.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreTask, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> permanentlyDeleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteTask, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getTasksCount({
    _i5.TaskStatus? status,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksCount, [], {
              #status: status,
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.TaskModel>> searchTasks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [query]),
            returnValue: _i3.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i4.TaskModel>>);

  @override
  _i3.Future<void> bulkDeleteTasks(List<String>? taskIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteTasks, [taskIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> bulkUpdateTasks(List<_i4.TaskModel>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateTasks, [tasks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TaskModel>> getTasksByTags(List<String>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByTags, [tags]),
            returnValue: _i3.Future<List<_i4.TaskModel>>.value(
              <_i4.TaskModel>[],
            ),
          )
          as _i3.Future<List<_i4.TaskModel>>);
}
